# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1502bf7c1a8591e6891ea5c1eafa21ade8586de5aa13305a4775e9841559caa15ba198ccea79df6dc03b94d3ee0dc2eea07919e6b92786b1b0485b2c86e125d

test:
  secret_key_base: 52d39058a021f7474460d828e663848323e94a4c7542774a7ac0718cf2f261b1d855814a59db58c6567c45480d1210295b13f912c30bda16c3dd504b9c2b2620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
